baseURL = "https://junuxyz.github.io/"
languageCode = "en-us"
title = "jlog"

[pagination]
  pagerSize = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

# Enable taxonomies
[taxonomies]
  tag = "tags"

# Configure permalinks
[permalinks]
  blog = "/blog/posts/:slug/"
  [permalinks.taxonomy]
    tags = "/blog/tags/"
  [permalinks.term]
    tags = "/blog/tags/:slug/"

[minify]
  disableXML = true
  minifyOutput = true

# Syntax highlighting configuration
[markup]
  [markup.highlight]
    noClasses = false
  
  # Enable math processing in markdown
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enable raw HTML in markdown (needed for math)
      unsafe = true
      hardWraps = true
    [markup.goldmark.parser]
      # Enable math delimiters
      wrapStandAloneImageWithinParagraph = false

[params]
  env = "production"
  description = "Personal blog and thoughts"
  author = "Junu"
  math = true
  
  # Social Icons
  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/junuxyz"
  [[params.socialIcons]]
    name = "Email"
    url = "mailto:jpjunior211@gmail.com"

# Main menu
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/blog/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/blog/tags/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 30
